# Generated by Django 5.0 on 2024-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_title_az_blogcategory_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='smalldescription',
            field=models.TextField(max_length=100, verbose_name='smalldescription'),
        ),
    ]
